const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.existsSync(__dirname+'/../src/core.js')?fs.readFileSync(__dirname+'/../src/core.js','utf8'):'';
vm.runInThisContext(source);const S=globalThis.Stewart;
assert.ok(S && typeof S.createGeometry==='function','Stewart mechanics core must exist');
const g=S.createGeometry();const home=S.homeState(g); const kin=S.kinematics(g,home);
assert.equal(kin.lengths.length,6);assert.ok(kin.lengths.every(x=>x>g.minLength && x<g.maxLength));
const poses=[[.018,-.025,.035,.06,-.07,.1],[-.04,.01,-.03,-.04,.06,-.12],[0,0,0,0,0,0]];
for(const v of poses){const st=S.cloneState(home);st.p=S.add(st.p,v.slice(0,3));st.q=S.qexp(v.slice(3));const lens=S.kinematics(g,st).lengths;const fk=S.forwardKinematics(g,lens,home);assert.ok(fk.ok);assert.ok(S.norm(S.sub(fk.state.p,st.p))<1e-7);assert.ok(S.norm(S.qlog(S.qmul(fk.state.q,S.qconj(st.q))))<1e-6);}
console.log('Initial kinematics acceptance passed');
let passed=3,metrics={};function test(name,f){f();passed++;console.log('PASS '+name);}
function close(a,b,t=1e-6){assert.ok(Math.abs(a-b)<t,`${a} != ${b} tolerance ${t}`);}
let seed=92;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
test('100 deterministic IK / independent local FK roundtrips',()=>{let max=0;for(let i=0;i<100;i++){let s=S.cloneState(home);s.p=S.add(s.p,Array.from({length:3},()=>.08*(rand()-.5)));s.q=S.qEuler(...Array.from({length:3},()=>.3*(rand()-.5)));let fk=S.forwardKinematics(g,S.kinematics(g,s).lengths,home);assert.ok(fk.ok);max=Math.max(max,S.norm(S.sub(s.p,fk.state.p)));}metrics.fk_max_position_error_m=max;});
const probe=S.cloneState(home);probe.p=[.021,-.031,.57];probe.q=S.qEuler(.13,-.07,.12);probe.spin=[.2,-.1,.3,-.2,.1,-.3];probe.v=[.06,-.035,.02,.14,-.08,.09,.3,-.2,.1,.25,-.15,.2];
test('Body linear and angular Jacobians match central differences',()=>{let e=1e-6,maxV=0,maxW=0,k=S.kinematics(g,probe);for(let j=0;j<12;j++){let v=S.zeros();v[j]=1;let kp=S.kinematics(g,S.shift(probe,v,e)),km=S.kinematics(g,S.shift(probe,v,-e));for(let b=0;b<k.bodies.length;b++){let fd=S.scale(S.sub(kp.bodies[b].pos,km.bodies[b].pos),1/(2*e));let fw=S.scale(S.qlog(S.qmul(kp.bodies[b].q,S.qconj(km.bodies[b].q))),1/(2*e));maxV=Math.max(maxV,S.norm(S.sub(fd,k.bodies[b].Jv.map(r=>r[j]))));maxW=Math.max(maxW,S.norm(S.sub(fw,k.bodies[b].Jw.map(r=>r[j]))));}for(let i=0;i<6;i++)close((kp.lengths[i]-km.lengths[i])/(2*e),k.J[i][j],1e-8);}assert.ok(maxV<1e-7);assert.ok(maxW<1e-7);metrics.body_jacobian_max_error=Math.max(maxV,maxW);});
test('Coupled mass matrix symmetric positive definite',()=>{let d=S.dynamics(g,probe);for(let a=0;a<12;a++)for(let b=0;b<12;b++)close(d.M[a][b],d.M[b][a],1e-12);for(let k=0;k<20;k++){let f=Array.from({length:12},()=>rand()-.5),a=S.solveSPD(d.M,f);assert.ok(S.dot(a,S.mv(d.M,a))>0);assert.ok(S.norm(S.sub(S.mv(d.M,a),f))<1e-7);}});
test('Gravity is the negative gradient of full multibody potential',()=>{let d=S.dynamics(g,probe,false),e=1e-6;for(let j=0;j<12;j++){let v=S.zeros();v[j]=1;let up=S.energy(g,S.shift(probe,v,e)).potential,um=S.energy(g,S.shift(probe,v,-e)).potential;close(d.G[j],-(up-um)/(2*e),2e-7);}});
test('Convective / gyroscopic bias satisfies kinetic-energy identity',()=>{let d=S.dynamics(g,probe),e=1e-5,mp=S.dynamics(g,S.shift(probe,probe.v,e),false).M,mm=S.dynamics(g,S.shift(probe,probe.v,-e),false).M;let md=mp.map((r,i)=>r.map((x,j)=>(x-mm[i][j])/(2*e)));let a=S.dot(probe.v,d.h),b=.5*S.dot(probe.v,S.mv(md,probe.v));close(a,b,1e-6);metrics.energy_identity_residual=Math.abs(a-b);});
test('Passive spring wrench is the negative potential gradient',()=>{let gz=S.createGeometry({gravity:0}),j=S.makeJointConfig(gz,home);for(let c of j){c.slider.mode='passive';c.slider.k=600;c.slider.c=0;c.base.k=3;c.top.k=4;c.base.c=0;c.top.c=0;}let st=S.cloneState(probe);st.v=S.zeros();let tau=S.passiveTau(gz,st,S.kinematics(gz,st),j),e=1e-6;for(let a=0;a<12;a++){let v=S.zeros();v[a]=1;let ep=S.energy(gz,S.shift(st,v,e),j).potential,em=S.energy(gz,S.shift(st,v,-e),j).potential;close(tau[a],-(ep-em)/(2*e),2e-6);}});
test('Gravity allocation excludes every passive motor',()=>{let sim=S.makeSimulation(g);sim.joints[0].slider.mode='passive';let d=S.dynamics(g,sim.state),cols=S.activeColumns(g,d.k,sim.joints),out=S.allocate(g,cols,S.scale(d.G,-1));assert.equal(cols.length,5);assert.equal(out.map['0:slider:0'],undefined);assert.ok(out.residualNorm>1e-4);metrics.five_motor_gravity_residual_N=out.residualNorm;});
test('Motor force limits hold under infeasible allocation',()=>{let sim=S.makeSimulation(g);for(let j of sim.joints)j.slider.max=1;let d=S.dynamics(g,sim.state),cols=S.activeColumns(g,d.k,sim.joints),out=S.allocate(g,cols,S.scale(d.G,-1));assert.ok(out.values.every(x=>Math.abs(x)<=1.0000001));assert.ok(out.residualNorm>10);});
test('All 18 joint groups accept independent active / passive modes',()=>{let sim=S.makeSimulation(g);for(let c of sim.joints){c.base.mode='active';c.top.mode='active';}let cols=S.activeColumns(g,S.kinematics(g,sim.state),sim.joints);assert.equal(cols.length,42);sim.joints[3].top.mode='passive';assert.equal(S.activeColumns(g,S.kinematics(g,sim.state),sim.joints).length,39);});
test('Invalid saved project is rejected',()=>{let o=S.snapshot(S.makeSimulation(g));o.state.p[0]=NaN;assert.throws(()=>S.restore(o));});
test('Project JSON roundtrip preserves all joint states',()=>{let sim=S.makeSimulation(g);sim.joints[2].base.mode='active';sim.joints[4].slider.k=321;let r=S.restore(JSON.parse(JSON.stringify(S.snapshot(sim))));assert.equal(r.joints[2].base.mode,'active');assert.equal(r.joints[4].slider.k,321);});
function run(sim,seconds){for(let i=0;i<Math.round(seconds/sim.settings.dt);i++){S.step(sim);assert.ok(!sim.halted,sim.error);}return sim;}
test('Full multibody gravity compensation holds rest without position PD',()=>{let sim=S.makeSimulation(g);sim.settings.mode='gravity';run(sim,.5);let err=S.norm(S.sub(sim.state.p,home.p));assert.ok(err<1e-6);metrics.gravity_only_drift_m=err;});
test('IK force controller tracks translation and rotation',()=>{let sim=S.makeSimulation(g);sim.target.p=[.025,-.020,.58];sim.target.q=S.qEuler(.06,-.07,.08);run(sim,1.3);let pe=S.norm(S.sub(sim.state.p,sim.target.p)),re=S.norm(S.qlog(S.qmul(sim.state.q,S.qconj(sim.target.q))));assert.ok(pe<.0015);assert.ok(re<.008);metrics.ik_position_error_m=pe;metrics.ik_rotation_error_rad=re;});
test('Compliance follows F / K and returns after releasing the load',()=>{let sim=S.makeSimulation(g);sim.settings.mode='compliance';sim.settings.translationK=800;sim.settings.external=[16,0,0,0,0,0];run(sim,1.5);let deflection=sim.state.p[0];close(deflection,16/800,.0015);sim.settings.external=S.zeros(6);run(sim,1.5);assert.ok(Math.abs(sim.state.p[0])<.001);metrics.compliance_deflection_m=deflection;metrics.compliance_return_error_m=Math.abs(sim.state.p[0]);});
test('Passive springs dissipate energy with motors off and gravity off',()=>{let sim=S.makeSimulation(S.createGeometry({gravity:0}));sim.settings.mode='free';for(let j of sim.joints){j.slider.mode='passive';j.slider.k=700;j.slider.c=40;j.base.k=.2;j.top.k=.2;}S.impulse(sim,[.2,-.1,.2],[.01,.01,0]);let E0=S.energy(sim.g,sim.state,sim.joints).total;run(sim,.5);let E1=S.energy(sim.g,sim.state,sim.joints).total;assert.ok(E1<E0*.15);metrics.passive_energy_ratio=E1/E0;});
test('Unpowered platform accelerates downward, rather than following target',()=>{let sim=S.makeSimulation(g);sim.settings.mode='free';run(sim,.04);assert.ok(sim.state.p[2]<g.homeZ-.002);assert.ok(sim.state.v[2]<-.15);metrics.unpowered_z_after_40ms_m=sim.state.p[2];});
test('Spherical active motors produce bounded physical torque',()=>{let sim=S.makeSimulation(g);sim.settings.mode='manual';for(let j of sim.joints)j.slider.manual=0;sim.joints[0].base.mode='active';sim.joints[0].base.manual=[0,0,2];S.step(sim);assert.equal(sim.last.forces['0:base:2'],2);assert.ok(S.norm(sim.state.v)>0);});
test('Inconsistent FK lengths fail explicitly',()=>{let r=S.forwardKinematics(g,[.1,2,.1,2,.1,2]);assert.ok(!r.ok);});
test('Geometry rejects non-finite and non-physical scalar fields',()=>{for(const o of [{payloadMass:NaN},{payloadZ:NaN},{baseZ:NaN},{basePair:NaN},{topPair:NaN},{minLength:NaN},{maxLength:NaN},{gravity:NaN},{gravity:-1},{barrelRadius:0},{rodRadius:-.01},{plateThickness:-.01}])assert.throws(()=>S.createGeometry(o),JSON.stringify(o));});
test('Project rejects non-finite spherical rest orientation',()=>{let o=S.snapshot(S.makeSimulation(g));o.joints[0].base.rest=[NaN,0,0,0];assert.throws(()=>S.restore(o));});
test('Inverse dynamics subtracts applied external wrench',()=>{let sim=S.makeSimulation(g),a=S.zeros();a[0]=.3;a[4]=.15;let without=S.inverseDynamics(sim,a);sim.settings.external=[13,-2,5,.3,-.2,.1];let withLoad=S.inverseDynamics(sim,a);for(let i=0;i<12;i++)close(without.tau[i]-withLoad.tau[i],i<6?sim.settings.external[i]:0,1e-9);metrics.inverse_dynamics_external_wrench_test=true;});
test('Actual force-driven IK enforces motor effort limits',()=>{let sim=S.makeSimulation(g);for(let j of sim.joints)j.slider.max=5;sim.target.p[2]+=.09;run(sim,.06);for(let [id,f] of Object.entries(sim.last.forces))if(id.includes(':slider:'))assert.ok(Math.abs(f)<=5.0000001);assert.ok(sim.last.saturated>0);});
test('42-axis active configuration integrates bounded physical motion',()=>{let sim=S.makeSimulation(g);for(let j of sim.joints){j.base.mode='active';j.top.mode='active';}sim.target.p[0]=.01;sim.target.q=S.qEuler(.02,-.01,.02);run(sim,.2);assert.equal(Object.keys(sim.last.forces).length,42);assert.ok(sim.state.p[0]>.001);for(let c of S.activeColumns(g,sim.last.k,sim.joints))assert.ok(Math.abs(sim.last.forces[c.id])<=c.cap+1e-8);});

console.log(JSON.stringify({passed,metrics},null,2));fs.writeFileSync(__dirname+'/core-results.json',JSON.stringify({passed,metrics},null,2));
