(function(){'use strict';const S=Stewart,$=id=>document.getElementById(id),deg=180/Math.PI;
let sim=S.makeSimulation(),renderer,selected={i:0,type:'slider'},running=true,trajectory='sway',speed=1,lastTime=0,accumulator=0,lastUI=0,lastSample=-1,records=[],fkEstimate=S.homeState(sim.g),telemetryFkEstimate=S.homeState(sim.g),fkResult=null,targetWarning='',toastTimer=0,lastRtf={wall:0,sim:0},rtf=0;
const modes={ik:['IK / PD','PD forces reduce leg-length error. Gravity compensation is optional.'],gravity:['GRAVITY','Compensates gravity of all moving bodies, without position feedback. External forces can still move the platform; modest joint damping remains.'],compliance:['COMPLIANCE','Allocates virtual spring and damper forces to active joints. A smaller stiffness K gives a softer response.'],manual:['MANUAL EFFORT','Uses manual joint forces and torques from the Joints tab. Automatic pose control and gravity compensation are off.'],free:['DRIVES OFF','Motor effort is zero. Gravity, passive joints, stroke stops and floor contact remain active.']};
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3300);}
function tab(name){if(!$('panel-'+name))return;document.querySelectorAll('.tab').forEach(e=>{e.classList.toggle('active',e.dataset.tab===name);e.setAttribute('aria-pressed',String(e.dataset.tab===name));});document.querySelectorAll('.panel').forEach(e=>e.classList.toggle('active',e.id==='panel-'+name));syncControls();}
function f(x,n=2){return Number.isFinite(x)?x.toFixed(n):'—';}
function rowRange(parent,key,label,value,min,max,step,unit,onChange){let d=document.createElement('div');d.className='slider-row';d.innerHTML=`<label for="${key}">${label}</label><input type="range" id="${key}" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${label}"><input type="number" id="${key}N" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${label} numeric value"><span>${unit}</span>`;parent.appendChild(d);let a=$(key),b=$(key+'N');for(let input of[a,b])input.addEventListener('input',()=>{let v=Number(input.value);if(!Number.isFinite(v)||input.value==='')return;v=S.clamp(v,+a.min,+a.max);a.value=v;b.value=v;onChange(v);});return d;}
function setRange(id,value){if(document.activeElement!==$(id))$(id).value=value;if(document.activeElement!==$(id+'N'))$(id+'N').value=value;}
function field(parent,key,label,value,min,max,step,unit,onChange){let d=document.createElement('div');d.className='form-row';d.innerHTML=`<label for="${key}">${label} <span class="unit-label">${unit||''}</span></label><input id="${key}" type="number" value="${value}" min="${min}" max="${max}" step="${step}">`;parent.appendChild(d);if(onChange)$(key).addEventListener('change',()=>{let v=+$(key).value;if($(key).value.trim()!==''&&Number.isFinite(v)&&v>=min&&v<=max)onChange(v);else{$(key).value=value;toast('Enter a number in the permitted range.');}});}
// One target owner: ball automatic, manual pose, or manual effort. Tabs only inspect.
function setMode(mode,stopTrajectory=true){
 if(!Object.hasOwn(modes,mode))return false;
 if(stopTrajectory){trajectory='none';$('trajectory').value='none';if(sim.ball)sim.ball.settings.control=false;window.lab?.clearLesson?.();}
 sim.settings.mode=mode;
 if(stopTrajectory&&['manual','free'].includes(mode)){running=false;accumulator=0;toast('Paused before changing motor effort. Set commands, then Run. Return to Ball Lab resumes automatic control.');}
 syncControls();return true;
}
function syncControls(){
 if(!$('pose0'))return;
 const mode=sim.settings.mode,automatic=!!sim.ball&&sim.ball.settings.control&&mode==='ik',servo=!!sim.actuator;
 document.querySelectorAll('[data-mode]').forEach(e=>{e.classList.toggle('active',e.dataset.mode===mode);e.setAttribute('aria-pressed',String(e.dataset.mode===mode));});
 $('modeBadge').textContent=automatic?'BALL AUTO / '+(servo?'SERVO':'IDEAL'):modes[mode][0]+(servo?' / SERVO':'');
 $('modeNote').textContent=automatic?'The ball controller owns the pose target. Choose IK / pose control to tilt manually, or use Ball Lab to change the ball target.':(servo&&mode==='ik'?'Encoder velocity and winding-current loops follow the pose target. Ideal length Kp/Kd are not used.':modes[mode][1])+(servo?' The 24 V drive remains active; electrical current can decay over time.':'');
 const poseDisabled=automatic||!['ik','compliance'].includes(mode);
 for(let i=0;i<6;i++)for(let id of['pose'+i,'pose'+i+'N']){$(id).disabled=poseDisabled;$(id).title=poseDisabled?'Select IK / pose control for manual platform targets.':'';}
 $('trajectory').disabled=automatic||mode!=='ik';
 $('gravityComp').disabled=!['ik','compliance'].includes(mode);
 for(let id of['translationK','translationD','rotationK','rotationD'])$(id).disabled=mode!=='compliance';
 $('gravityDamping').disabled=mode!=='gravity';$('complianceCard').style.opacity=mode==='compliance'?'1':'.68';
 const c=sim.joints[selected.i][selected.type],linear=selected.type==='slider';
 $('jointK').disabled=$('jointC').disabled=c.mode!=='passive';
 $('jointKp').disabled=$('jointKd').disabled=c.mode!=='active'||mode!=='ik'||(servo&&linear);
 $('jointKp').title=$('jointKd').title=servo&&linear?'The servo uses its own encoder/current loops. These gains apply only to the ideal IK profile.':'';
 $('jointMax').disabled=c.mode!=='active';
 $('jointManual').querySelectorAll('input').forEach(e=>{e.disabled=c.mode!=='active'||mode!=='manual';e.title=e.disabled?'Select Manual effort and an active joint to use this command.':'';});
 if($('jointUsage'))$('jointUsage').textContent=servo&&linear?'Servo profile: edit current/speed limits in Ball Lab. Ideal Kp/Kd are not used.':mode==='manual'?'Manual effort is applied only to active joints. Position holding is off.':'Passive k/c act without a motor. Active Kp/Kd apply in ideal IK; manual effort needs Manual mode.';
 $('exportCsv').textContent='Platform CSV';$('reset').textContent=sim.ball?'↺ Reset lab':'↺ Reset platform';
 $('reset').title=sim.ball?'Restore the tested Ball Lab setup; clears this run.':'Reset state and controls, keeping design geometry.';
 $('pushX').textContent='↗ Push plate';$('pushX').title='Platform impulse +X 2 N·s; different from pushing the ball.';
 $('energyValue').title='Mechanism rigid-body and spring energy only; excludes the free ball and electrical energy.';
}
function invalidateFk(resetSeed=false){fkResult=null;if(resetSeed){fkEstimate=S.homeState(sim.g);telemetryFkEstimate=S.homeState(sim.g);}if($('applyFk'))$('applyFk').disabled=true;if($('fkResult')){$('fkResult').textContent='Inputs or project changed. Copy lengths and solve again.';$('fkResult').className='readout';}if(renderer)renderer.previewPose=null;}
function syncPose(){let v=[...S.scale(sim.target.p,1000),...S.scale(S.toEuler(sim.target.q),deg)];v.forEach((x,i)=>setRange('pose'+i,+f(x,i<3?1:2)));}
function setTarget(st){let check=S.feasible(sim.g,st);trajectory='none';$('trajectory').value='none';if(!check.ok){targetWarning='Target rejected: '+check.reason;return false;}targetWarning='';sim.target=S.cloneState(st);syncPose();return true;}
function poseChange(){let values=Array.from({length:6},(_,i)=>+$('pose'+i+'N').value),st=S.cloneState(sim.target);st.p=S.scale(values.slice(0,3),.001);st.q=S.qEuler(...S.scale(values.slice(3),1/deg));setTarget(st);}
function jointLabel(type){return{base:'B',slider:'P',top:'T'}[type];}
function renderJointMatrix(){let p=$('jointMatrix');p.innerHTML='<span></span><span class="colhead">BASE<br>Spherical · 3R</span><span class="colhead">LINEAR<br>Prismatic · 1P</span><span class="colhead">TOP<br>Spherical · 3R</span>';
 for(let i=0;i<6;i++){let span=document.createElement('span');span.className='rowhead';span.textContent='L'+(i+1);p.appendChild(span);for(let type of['base','slider','top']){let c=sim.joints[i][type],button=document.createElement('button');button.className='joint-btn '+(c.mode==='active'?'activejoint':'passivejoint')+(selected.i===i&&selected.type===type?' selected':'');button.dataset.joint=`${i}:${type}`;button.innerHTML=`<span class="dot"></span>${jointLabel(type)}${i+1} ${c.mode==='active'?'ACTIVE':'PASSIVE'}`;button.addEventListener('click',()=>selectJoint({i,type}));p.appendChild(button);}}
}
function selectJoint(value){selected=value;tab('joints');renderJointMatrix();syncJointEditor();}
function syncJointEditor(){let c=sim.joints[selected.i][selected.type],linear=selected.type==='slider',pre=jointLabel(selected.type)+(selected.i+1);$('jointTitle').textContent=pre+' · '+({base:'Base spherical joint',slider:'Prismatic joint',top:'Top spherical joint'}[selected.type]);$('jointType').textContent=linear?'PRISMATIC / AXIAL TRANSLATION':'SPHERICAL / THREE ROTATIONAL AXES';$('jointDof').textContent=linear?'1 DOF':'3 DOF';$('jointMode').value=c.mode;
 for(let[key,id]of[['k','jointK'],['c','jointC'],['kp','jointKp'],['kd','jointKd'],['max','jointMax']]){$(id).value=c[key];$(id).step=linear?'1':'.01';$(id).max=linear?(key==='k'||key==='kp'?50000:2000):(key==='k'||key==='kp'?200:key==='max'?50:20);}
 $('jointK').disabled=$('jointC').disabled=c.mode!=='passive';$('jointKp').disabled=$('jointKd').disabled=$('jointMax').disabled=c.mode!=='active';$('kUnit').textContent=linear?'N/m':'N·m/rad';$('cUnit').textContent=linear?'N·s/m':'N·m·s/rad';$('limitUnit').textContent=linear?'±N':'±N·m / axis';$('restRead').textContent=linear?'rest length: '+f(c.rest*1000,2)+' mm':'rest quaternion [w,x,y,z]\n'+c.rest.map(x=>f(x,4)).join('  ');
 let m=$('jointManual');m.innerHTML='';if(linear)field(m,'jointManual0','Axial force',c.manual,-c.max,c.max,1,'N',v=>c.manual=v);else for(let a=0;a<3;a++)field(m,'jointManual'+a,'Torque '+['X','Y','Z'][a],c.manual[a],-c.max,c.max,.1,'N·m',v=>c.manual[a]=v);syncControls();
}
function syncCommon(){syncPose();setMode(sim.settings.mode,false);$('gravityComp').checked=sim.settings.gravityComp;for(let id of['translationK','translationD','rotationK','rotationD','gravityDamping'])$(id).value=sim.settings[id];$('gravityValue').value=sim.g.gravity;$('timeStep').value=sim.settings.dt;sim.settings.external.forEach((v,i)=>setRange('external'+i,v));renderJointMatrix();syncJointEditor();buildDesignFields();$('trajectory').value=trajectory;}
function reset(g=sim.g){sim=S.makeSimulation(S.createGeometry({...g,motorReflectedMass:0}));trajectory='none';targetWarning='';records=[];lastSample=-1;invalidateFk(true);window.lab?.clearLesson?.();accumulator=0;lastTime=0;running=!matchMedia('(prefers-reduced-motion: reduce)').matches;syncCommon();}
function resetExperiment(){if(sim.ball&&window.lab?.startBall)window.lab.startBall();else reset();updateTelemetry();}
function preset(name){reset();if(name==='gravity')setMode('gravity');if(name==='compliance'){setMode('compliance');sim.settings.translationK=800;sim.settings.external=[16,0,0,0,0,0];}if(name==='passive'){setMode('free');for(let j of sim.joints)j.slider.mode='passive';}if(name==='off')setMode('free');syncCommon();toast({gravity:'Gravity compensation only; no position feedback.',compliance:'K=800 N/m; applied +X 16 N. Release it in Dynamics.',passive:'All six prismatic joints now use passive springs and dampers.',off:'Zero motor effort. Gravity and passive physics remain active.'}[name]);}
function updateTrajectory(){if(trajectory==='none'||!['ik','compliance'].includes(sim.settings.mode))return;let t=sim.state.t,st=S.homeState(sim.g);if(trajectory==='sway'){st.p=[.035*Math.sin(.7*t),.025*Math.sin(.5*t),sim.g.homeZ+.02*Math.sin(.8*t)];st.q=S.qEuler(.07*Math.sin(.9*t),.07*Math.sin(.7*t),.10*Math.sin(.5*t));}else if(trajectory==='heave')st.p[2]+=.035*Math.sin(1.2*t);else st.q=S.qEuler(.10*Math.sin(.8*t),.10*(Math.cos(.8*t)-1)/2,0);
 let check=S.feasible(sim.g,st);if(check.ok)sim.target=st;else{trajectory='none';$('trajectory').value='none';targetWarning='Trajectory left this geometry’s checked workspace. Holding the last accepted target.';}}
function exportFile(name,text,type='application/json'){let b=new Blob([text],{type}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function collectSample(k){if(sim.state.t-lastSample<.045)return;lastSample=sim.state.t;let s=sim.state,forces=sim.last?.forces||{},r={t:s.t,p:s.p.slice(),q:s.q.slice(),v:s.v.slice(),targetP:sim.target.p.slice(),targetQ:sim.target.q.slice(),lengths:k.lengths.slice(),forces:{...forces},mode:sim.settings.mode,external:sim.settings.external.slice(),gravity:sim.g.gravity,dt:sim.settings.dt,gains:[sim.settings.translationK,sim.settings.translationD,sim.settings.rotationK,sim.settings.rotationD],joints:sim.joints.map(j=>Object.fromEntries(['base','slider','top'].map(type=>[type,{mode:j[type].mode,k:j[type].k,c:j[type].c,kp:j[type].kp,kd:j[type].kd,max:j[type].max}])))};records.push(r);if(records.length>10000)records.shift();}
function csv(){if(!records.length){toast('No recorded samples yet. Run the simulation first.');return;}let heads=['time_s','mode','px_m','py_m','pz_m','qw','qx','qy','qz',...Array.from({length:12},(_,i)=>'velocity_'+i),...['tx_m','ty_m','tz_m','tqw','tqx','tqy','tqz'],...Array.from({length:6},(_,i)=>'length_'+(i+1)+'_m'),...['Fx_N','Fy_N','Fz_N','Tx_Nm','Ty_Nm','Tz_Nm'],'gravity_mps2','dt_s','task_K_Npm','task_D_Nspm','task_Kr_Nmprad','task_Dr_Nmsprad'];
 for(let i=0;i<6;i++)for(let type of['base','slider','top']){for(let key of['mode','k','c','kp','kd','max'])heads.push(`${jointLabel(type)}${i+1}_${key}`);for(let a=0;a<(type==='slider'?1:3);a++)heads.push(`${jointLabel(type)}${i+1}_effort_${a}_${type==='slider'?'N':'Nm'}`);}
 let lines=[heads.join(',')];for(let r of records){let v=[r.t,r.mode,...r.p,...r.q,...r.v,...r.targetP,...r.targetQ,...r.lengths,...r.external,r.gravity,r.dt,...r.gains];for(let i=0;i<6;i++)for(let type of['base','slider','top']){let c=r.joints[i][type];for(let key of['mode','k','c','kp','kd','max'])v.push(c[key]);for(let a=0;a<(type==='slider'?1:3);a++)v.push(r.forces[`${i}:${type}:${a}`]||0);}lines.push(v.map(x=>typeof x==='number'?x.toPrecision(10):x).join(','));}exportFile('stewart-telemetry.csv',lines.join('\n'),'text/csv;charset=utf-8');toast(`${records.length} samples exported to CSV.`);}
const geometryFields=[['baseRadius','Base radius',1000,180,650,5,'mm'],['topRadius','Platform radius',1000,120,450,5,'mm'],['homeZ','Home height',1000,300,800,5,'mm'],['basePair','Base pair half-angle',1,5,28,.5,'deg'],['topPair','Top pair half-angle',1,5,28,.5,'deg'],['minLength','Minimum leg length',1000,200,650,5,'mm'],['maxLength','Maximum leg length',1000,350,1000,5,'mm'],['barrelLength','Barrel length',1000,220,550,5,'mm'],['rodLength','Rod length',1000,220,550,5,'mm']],massFields=[['platformMass','Platform mass',1,.5,30,.1,'kg'],['payloadMass','Attached payload',1,0,30,.1,'kg'],['payloadZ','Payload CoM height',1000,50,200,5,'mm'],['barrelMass','Mass per barrel',1,.1,3,.05,'kg'],['rodMass','Mass per rod',1,.05,3,.05,'kg']];
function buildDesignFields(){for(let[name,items]of[['geometryInputs',geometryFields],['massInputs',massFields]]){let p=$(name);p.innerHTML='';for(let[k,label,mul,min,max,step,u]of items)field(p,'geo_'+k,label,+f(sim.g[k]*mul,3),min,max,step,u);}
 let check=S.feasible(sim.g,S.homeState(sim.g)),total=sim.g.platformMass+sim.g.payloadMass+6*(sim.g.barrelMass+sim.g.rodMass);$('designStatus').classList.remove('bad');$('designStatus').textContent=`Moving mass: ${f(total,2)} kg\nPlatform: 6 DOF / internal spin: 6 DOF\nHome cond(J): ${f(check.condition,2)}\nStroke: ${f(sim.g.minLength*1000,0)}–${f(sim.g.maxLength*1000,0)} mm\nUnits: m · kg · s · N · rad`;}
function applyGeometry(){try{let o={...sim.g};for(let[k,,mul,min,max]of[...geometryFields,...massFields]){let v=+$('geo_'+k).value;if($('geo_'+k).value.trim()===''||!Number.isFinite(v)||v<min||v>max)throw Error(k+': check input range.');o[k]=v/mul;}let g=S.createGeometry(o),check=S.feasible(g,S.homeState(g));if(!check.ok)throw Error('Invalid home assembly: '+check.reason);reset(g);renderer.home();toast('Rebuilt using the new geometry and mass.');}catch(e){toast(e.message);$('designStatus').textContent=e.message;$('designStatus').classList.add('bad');}}
function chart(){let c=$('positionChart'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),w=rect.width,h=rect.height;c.width=Math.max(1,w*dpr);c.height=Math.max(1,h*dpr);ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);let data=records.filter(r=>r.t>sim.state.t-12),vals=data.flatMap(r=>[r.p[2]*1000,r.targetP[2]*1000]);if(!vals.length)vals=[sim.g.homeZ*1000];let min=Math.min(...vals)-3,max=Math.max(...vals)+3;if(max-min<10){min-=5;max+=5;}let x0=33,x1=w-8,y0=9,y1=h-17,t0=Math.max(0,sim.state.t-12),t1=Math.max(12,sim.state.t);ctx.font='9px monospace';ctx.lineWidth=1;
 for(let i=0;i<3;i++){let v=min+(max-min)*i/2,y=y1-(y1-y0)*i/2;ctx.strokeStyle='#e6edf0';ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x1,y);ctx.stroke();ctx.fillStyle='#91a1ac';ctx.fillText(v.toFixed(0),0,y+3);}for(let[key,color,dash]of[['targetP','#c0956e',[4,3]],['p','#188f8b',[]]]){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=1.7;ctx.setLineDash(dash);data.forEach((r,i)=>{let x=x0+(r.t-t0)/(t1-t0)*(x1-x0),y=y1-(r[key][2]*1000-min)/(max-min)*(y1-y0);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}ctx.setLineDash([]);ctx.fillStyle='#91a1ac';ctx.fillText(t0.toFixed(0)+'s',x0,h-3);ctx.fillText(t1.toFixed(0)+'s',x1-17,h-3);}
function updateTelemetry(){let s=sim.state,k=S.kinematics(sim.g,s),pe=S.norm(S.sub(s.p,sim.target.p)),re=S.norm(S.qlog(S.qmul(s.q,S.qconj(sim.target.q))))*deg,c=S.condition(sim.g,k),E=S.energy(sim.g,s,sim.joints);$('positionError').textContent=f(pe*1000,2);$('angleError').textContent=f(re,2);$('heightValue').textContent=f(s.p[2]*1000,1);$('timeBadge').textContent=f(s.t,2)+' s';$('liveBadge').innerHTML='<span class="dot"></span>'+(sim.halted?'SAFETY STOP':running?'RUNNING':'PAUSED');$('liveBadge').style.color=sim.halted?'#bd5647':running?'#168679':'#8a9399';$('playPause').textContent=sim.halted?'Numerical stop':running?'Ⅱ Pause':'▶ Run';let n=sim.joints.filter(j=>j.slider.mode==='active').length;$('activeSummary').textContent=`${n} active P / ${6-n} passive P`;
 for(let i=0;i<6;i++){let force=sim.last?.forces[i+':slider:0']||0,cap=sim.joints[i].slider.max;$('force'+i).textContent=f(force,1);$('bar'+i).style.width=Math.min(100,Math.abs(force)/Math.max(cap,1)*100)+'%';$('bar'+i).style.background=sim.joints[i].slider.mode==='active'?'#269e98':'#d9a055';$('flabel'+i).title=`L${i+1}: ${f(k.lengths[i]*1000,2)} mm | ${sim.joints[i].slider.mode} | ${f(force,2)} N`;}
 let fk=S.forwardKinematics(sim.g,k.lengths,telemetryFkEstimate);if(fk.ok)telemetryFkEstimate=fk.state;$('conditionValue').textContent='cond(J) '+f(c.condition,2);$('fkValue').textContent='FK '+(fk.ok?f(fk.residual*1e6,3)+' µm':'Not converged');$('energyValue').textContent='E '+f(E.total,2)+' J';$('allocationValue').textContent='Allocation residual '+f(sim.last?.allocation.residualNorm||0,3)+' N*';$('saturationValue').textContent='Saturated '+(sim.last?.saturated||0)+' axes';
 let warnings=[];if(targetWarning)warnings.push(targetWarning);if(sim.halted)warnings.push(sim.error);if(c.condition>60)warnings.push('Near-singular pose: high leg-Jacobian condition number.');if(sim.last?.allocation.residualNorm>1)warnings.push('Cannot allocate the requested effort. Check active axes and effort limits.');if(sim.last?.stopCount)warnings.push('A stroke stop or platform-floor contact is active.');if(sim.last?.saturated)warnings.push('Some motors have reached their effort limits.');$('notice').textContent=warnings.join(' ');$('notice').className='notice'+(warnings.length?' visible':'')+(sim.halted?' error':'');
 if(trajectory!=='none'||(sim.ball&&sim.ball.settings.control))syncPose();let kt=S.kinematics(sim.g,sim.target);$('ikReadout').textContent=kt.lengths.map((l,i)=>`L${i+1}    ${f(l*1000,3).padStart(9)} mm`).join('\n');let check=S.feasible(sim.g,sim.target);$('workspaceReadout').textContent=`Target: ${check.ok?'Within checks':'Outside checks'} · cond(J) ${f(check.condition,2)} · rank ${check.rank}/6`;
 let j=sim.joints[selected.i][selected.type],id=selected.i+':'+selected.type;if(selected.type==='slider')$('jointLive').textContent=`Length    ${f(k.lengths[selected.i]*1000,3)} mm\nSpeed     ${f(S.dot(k.J[selected.i],s.v)*1000,3)} mm/s\nEffort    ${f(sim.last?.forces[id+':0']||0,3)} N`;
 else{let l=k.legs[selected.i],w=S.mv(selected.type==='base'?l.Jw:l.Jrel,s.v);$('jointLive').textContent=`|angular speed|  ${f(S.norm(w),4)} rad/s\nActual torque [world X,Y,Z]\n${[0,1,2].map(a=>f(sim.last?.forces[id+':'+a]||0,3)).join('  ')} N·m`;}
 $('dynamicsReadout').textContent=`T  ${f(E.kinetic,5)} J\nV  ${f(E.potential,5)} J\n|v| ${f(S.norm(s.v.slice(0,3)),4)} m/s\n|ω| ${f(S.norm(s.v.slice(3,6)),4)} rad/s\naz ${f(sim.last?.acceleration[2]||0,4)} m/s²\nFixed dt ${f(sim.settings.dt*1000,1)} ms`;$('solverStatus').textContent=`REDUCED MULTIBODY · ${f(sim.settings.dt*1000,1)} ms`;$('rtf').textContent='Real-time factor '+f(rtf,2)+'×';collectSample(k);syncControls();chart();}
function setup(){
 document.querySelectorAll('.tab').forEach(e=>e.addEventListener('click',()=>tab(e.dataset.tab)));document.querySelectorAll('[data-mode]').forEach(e=>e.addEventListener('click',()=>setMode(e.dataset.mode)));document.querySelectorAll('[data-preset]').forEach(e=>e.addEventListener('click',()=>preset(e.dataset.preset)));
 for(let i=0;i<6;i++)rowRange($('poseSliders'),'pose'+i,['X','Y','Z','Roll','Pitch','Yaw'][i],i===2?550:0,i===2?300:i<3?-120:-25,i===2?800:i<3?120:25,i<3?1:.1,i<3?'mm':'deg',poseChange);
 $('gravityComp').addEventListener('change',()=>sim.settings.gravityComp=$('gravityComp').checked);for(let id of['translationK','translationD','rotationK','rotationD','gravityDamping'])$(id).addEventListener('change',()=>{let v=+$(id).value;if($(id).value.trim()!==''&&Number.isFinite(v)&&v>=+$(id).min&&v<=+$(id).max)sim.settings[id]=v;else{$(id).value=sim.settings[id];toast('Control gain is outside the permitted range.');}});
 $('homeTarget').onclick=()=>{setTarget(S.homeState(sim.g));setMode('ik');};$('holdCurrent').onclick=()=>{setTarget(sim.state);setMode('ik');};$('trajectory').onchange=()=>{trajectory=$('trajectory').value;setMode('ik',false);};$('speed').onchange=()=>speed=+$('speed').value;
 $('playPause').onclick=()=>{if(sim.halted){toast('Reset before running again.');return;}running=!running;accumulator=0;updateTelemetry();};$('reset').onclick=resetExperiment;$('pushX').onclick=()=>{S.impulse(sim,[2,0,0]);toast('+X impulse: 2 N·s');};$('impulseZ').onclick=()=>{S.impulse(sim,[0,0,-2]);toast('−Z impulse: 2 N·s');};$('impulseYaw').onclick=()=>S.impulse(sim,[0,0,0],[0,0,.2]);
 $('cameraHome').onclick=()=>renderer.home();$('ghostToggle').onclick=()=>{renderer.showGhost=!renderer.showGhost;$('ghostToggle').classList.toggle('on',renderer.showGhost);};$('forceArrowToggle').onclick=()=>{renderer.showForces=!renderer.showForces;$('forceArrowToggle').classList.toggle('on',renderer.showForces);};$('capture').onclick=()=>{renderer.render(sim,selected);let a=document.createElement('a');a.download='stewart-view.png';a.href=$('scene').toDataURL('image/png');a.click();};
 $('jointMode').onchange=()=>{sim.joints[selected.i][selected.type].mode=$('jointMode').value;renderJointMatrix();syncJointEditor();};for(let[id,key]of[['jointK','k'],['jointC','c'],['jointKp','kp'],['jointKd','kd'],['jointMax','max']])$(id).addEventListener('change',()=>{let v=+$(id).value,c=sim.joints[selected.i][selected.type];if($(id).value.trim()!==''&&Number.isFinite(v)&&v>=+$(id).min&&v<=+$(id).max)c[key]=v;else{$(id).value=c[key];toast('Check the permitted joint coefficient range.');}if(key==='max')syncJointEditor();});
 $('captureJointRest').onclick=()=>{let k=S.kinematics(sim.g,sim.state),i=selected.i,c=sim.joints[i][selected.type];c.rest=selected.type==='slider'?k.lengths[i]:(selected.type==='base'?k.legs[i].q.slice():k.legs[i].relative.slice());syncJointEditor();toast('Captured the selected joint’s current configuration as rest.');};$('captureAllRest').onclick=()=>{S.captureRest(sim.joints,sim.g,sim.state);syncJointEditor();toast('Captured all eighteen joint rest configurations.');};$('allActive').onclick=()=>{for(let j of sim.joints)j.slider.mode='active';renderJointMatrix();syncJointEditor();};$('allPassive').onclick=()=>{for(let j of sim.joints)j.slider.mode='passive';renderJointMatrix();syncJointEditor();};
 let lens=S.kinematics(sim.g,sim.state).lengths;for(let i=0;i<6;i++)rowRange($('fkInputs'),'fk'+i,'L'+(i+1),+f(lens[i]*1000,2),200,1000,.1,'mm',()=>invalidateFk());function copyLengths(k){k.lengths.forEach((v,i)=>setRange('fk'+i,+f(v*1000,5)));invalidateFk();}$('fkFromActual').onclick=()=>copyLengths(S.kinematics(sim.g,sim.state));$('fkFromTarget').onclick=()=>copyLengths(S.kinematics(sim.g,sim.target));
 $('solveFk').onclick=()=>{try{let lengths=Array.from({length:6},(_,i)=>+$('fk'+i+'N').value/1000);fkResult=S.forwardKinematics(sim.g,lengths,$('fkSeed').value==='home'?S.homeState(sim.g):fkEstimate);let r=fkResult,check=r.ok?S.feasible(sim.g,r.state):{ok:false};$('fkResult').className='readout '+(r.ok&&check.ok?'good':'bad');$('fkResult').textContent=r.ok?`Converged in ${r.iterations} iterations · residual ${r.residual.toExponential(2)} m\np [mm] ${r.state.p.map(v=>f(v*1000,3)).join(', ')}\nRPY [°] ${S.toEuler(r.state.q).map(v=>f(v*deg,3)).join(', ')}\n${check.ok?'Workspace checks passed':check.reason}`:`Not converged · residual ${f(r.residual,6)} m\n${r.reason}`;$('applyFk').disabled=!(r.ok&&check.ok);if(r.ok)fkEstimate=r.state;}catch(e){$('fkResult').textContent=e.message;$('fkResult').className='readout bad';$('applyFk').disabled=true;}};$('applyFk').onclick=()=>{if(fkResult?.ok){setTarget(fkResult.state);setMode('ik');toast('FK solution applied as an IK target, without overwriting the physical pose.');}};
 for(let i=0;i<6;i++)rowRange($('externalInputs'),'external'+i,['Fx','Fy','Fz','Tx','Ty','Tz'][i],0,i<3?-100:-15,i<3?100:15,i<3?1:.1,i<3?'N':'N·m',v=>sim.settings.external[i]=v);
 $('releaseForce').onclick=()=>{sim.settings.external=S.zeros(6);sim.settings.external.forEach((v,i)=>setRange('external'+i,v));toast('All sustained external forces released.');};$('gravityValue').onchange=()=>{let v=+$('gravityValue').value;if($('gravityValue').value.trim()!==''&&Number.isFinite(v)&&v>=0&&v<=30)sim.g.gravity=v;else $('gravityValue').value=sim.g.gravity;};$('timeStep').onchange=()=>sim.settings.dt=+$('timeStep').value;
 for(let i=0;i<6;i++)rowRange($('accelerationInputs'),'acc'+i,['ax','ay','az','αx','αy','αz'][i],0,i<3?-10:-20,i<3?10:20,.1,i<3?'m/s²':'rad/s²',()=>{});
 $('calculateInverse').onclick=()=>{try{let a=[...Array.from({length:6},(_,i)=>+$('acc'+i+'N').value),...S.zeros(6)],r=S.inverseDynamics(sim,a);$('inverseReadout').textContent=Array.from({length:6},(_,i)=>`P${i+1}  ${f(r.map[i+':slider:0']||0,3).padStart(9)} N`).join('\n')+`\nResidual ${f(r.residualNorm,5)} N*\nSaturated ${r.saturated} axes`;}catch(e){$('inverseReadout').textContent=e.message;}};
 $('applyGeometry').onclick=applyGeometry;$('defaultGeometry').onclick=()=>{reset(S.createGeometry());renderer.home();};$('saveDesign').onclick=()=>exportFile('stewart-design.json',JSON.stringify({schema:'stewart-design/1',geometry:{...sim.g,motorReflectedMass:0},units:'SI',model:'finite-mass reduced 6-SPS, 12 generalized speeds',boundaries:'Geometry only; no saved pose, controller, ball or servo state. Use Save project to resume an experiment. Not manufacturing or hardware validation.'},null,2));
 $('saveProject').onclick=()=>exportFile('stewart-project.json',JSON.stringify(S.snapshot(sim),null,2));$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async e=>{try{let file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('Project JSON must be at most 2 MB.');let obj=JSON.parse(await file.text()),next=S.restore(obj);sim=next;running=false;trajectory='none';targetWarning='';invalidateFk(true);window.lab?.clearLesson?.();records=[];lastSample=-1;accumulator=0;lastTime=0;syncCommon();tab(sim.ball?'ball':'control');updateTelemetry();document.dispatchEvent(new Event('stewart:loaded'));toast('Project loaded and paused. Inspect it before pressing Run.');}catch(err){toast('Import failed: '+err.message);}finally{e.target.value='';}};$('exportCsv').onclick=csv;
 let helpFocus=null;
 function closeHelp(){if(!$('helpModal').classList.contains('show'))return;$('helpModal').classList.remove('show');helpFocus?.focus();}
 $('helpOpen').onclick=()=>{helpFocus=document.activeElement;running=false;accumulator=0;$('helpModal').classList.add('show');$('helpClose').focus();updateTelemetry();};
 $('helpClose').onclick=$('helpStart').onclick=closeHelp;
 $('helpModal').onclick=e=>{if(e.target===$('helpModal'))closeHelp();};
 document.addEventListener('keydown',e=>{
  if($('helpModal').classList.contains('show')){if(e.code==='Escape'){e.preventDefault();closeHelp();}if(e.key==='Tab'){let a=[$('helpClose'),$('helpStart')],i=a.indexOf(document.activeElement);e.preventDefault();a[(i+(e.shiftKey?-1:1)+a.length)%a.length].focus();}return;}
  if(e.defaultPrevented||document.activeElement.closest('input,select,textarea,button,a,summary,[contenteditable=true]'))return;
  if(e.code==='Space'){e.preventDefault();$('playPause').click();}if(e.code==='KeyR')$('reset').click();
 });document.addEventListener('visibilitychange',()=>{lastTime=0;accumulator=0;});
 $('forceList').innerHTML=Array.from({length:6},(_,i)=>`<div class="force-item" id="flabel${i}"><span>L${i+1}</span><div class="force-track"><div class="force-fill" id="bar${i}"></div></div><b id="force${i}">0.0</b><span class="force-sign">N</span></div>`).join('');$('labels').innerHTML=Array.from({length:6},(_,i)=>`<div class="label" id="label${i}">L${i+1}</div>`).join('');syncCommon();
}
function frame(now){try{let elapsed=lastTime?Math.min((now-lastTime)/1000,.08):0;lastTime=now;if(running&&!sim.halted&&!document.hidden){accumulator+=elapsed*speed;let start=performance.now(),steps=0;while(accumulator>=sim.settings.dt&&steps<80&&performance.now()-start<13){updateTrajectory();S.step(sim);accumulator-=sim.settings.dt;steps++;if(sim.halted){running=false;break;}}accumulator=Math.min(accumulator,.1);}renderer.render(sim,selected);
 if(renderer.lastKin)for(let l of renderer.lastKin.legs){let p=renderer.project(S.add(l.b,S.scale(l.n,.21))),el=$('label'+l.index);el.style.left=p[0]+'px';el.style.top=p[1]+'px';el.style.display=p[2]<1?'block':'none';}
 if(now-lastUI>110){updateTelemetry();lastUI=now;}if(now-lastRtf.wall>700){rtf=(sim.state.t-lastRtf.sim)/((now-lastRtf.wall)/1000);if(rtf<0)rtf=0;lastRtf={wall:now,sim:sim.state.t};}
 }catch(e){running=false;sim.halted=true;sim.error=e.message;$('notice').textContent=e.message;$('notice').className='notice visible error';console.error(e);}requestAnimationFrame(frame);}
try{renderer=new StewartRenderer($('scene'),selectJoint);setup();window.lab={get sim(){return sim;},get running(){return running;},set running(v){running=!!v;},get renderer(){return renderer;},get records(){return records;},setMode,reset,resetExperiment,preset,selectJoint,setTarget,tab,updateTelemetry,toast,syncControls,runFor(seconds){running=false;trajectory='none';$('trajectory').value='none';for(let i=0;i<Math.round(seconds/sim.settings.dt);i++)S.step(sim);updateTelemetry();renderer.render(sim,selected);return S.snapshot(sim);},saveSnapshot:()=>S.snapshot(sim)};window.__stewartReady=true;requestAnimationFrame(frame);}catch(e){$('failure').style.display='flex';$('failure').textContent='Initialization failed: '+e.message;console.error(e);}
})();
